---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  labels:
    argocd.argoproj.io/instance: argo
spec:
  project: home-kubernetes
  sources:
    - repoURL: https://github.com/hboyd2003/cluster-template.git
      path: kubernetes/apps/argo-system/argo
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/argoproj/argo-helm
      chart: argo-cd
      targetRevision: 7.7.6
      helm:
        releaseName: argo
        valueFiles:
          - $repo/kubernetes/apps/argo-system/argo/values.sops.yaml
  destination:
    name: in-cluster
    namespace: argo-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
