crds:
    install: true
global:
    domain: argo.przmo.com
configs:
    params:
        server.insecure: true
    cm:
        statusbadge.enabled: true
        kustomize.buildOptions: --enable-alpha-plugins --enable-exec
        helm.valuesFileSchemes: secrets+gpg-import, secrets+gpg-import-kubernetes, secrets+age-import, secrets+age-import-kubernetes, secrets, secrets+literal, https
        resource.exclusions: |
            - apiGroups:
                - cilium.io
              kinds:
                - CiliumIdentity
              clusters:
                - "*"
    secret:
        argocdServerAdminPassword: null
        argocdServerAdminPasswordMtime: 2024-12-10T19:53:21
        githubSecret: e52287de94df5020269abebc64aa2b12
controller:
    replicas: 2
    metrics:
        enabled: true
        applicationLabels:
            enabled: true
        serviceMonitor:
            enabled: true
            additionalLabels:
                release: kube-prometheus-stack
dex:
    replicas: 2
    metrics:
        enabled: true
        serviceMonitor:
            enabled: true
            additionalLabels:
                release: kube-prometheus-stack
redis:
    metrics:
        enabled: true
        serviceMonitor:
            enabled: true
            additionalLabels:
                release: kube-prometheus-stack
server:
    replicas: 2
    allowAnyNamespace: true
    ingress:
        enabled: true
        ingressClassName: external
        annotations:
            external-dns.alpha.kubernetes.io/target: external.przmo.com
        hostname: argo.przmo.com
    metrics:
        enabled: true
        serviceMonitor:
            enabled: true
            additionalLabels:
                release: kube-prometheus-stack
notifications:
    replicas: 2
    metrics:
        enabled: true
        serviceMonitor:
            enabled: true
            additionalLabels:
                release: kube-prometheus-stack
repoServer:
    replicas: 2
    serviceAccount:
        create: true
        name: argocd-repo-server
    rbac:
        - apiGroups:
            - ""
          resources:
            - secrets
          verbs:
            - get
    env:
        - name: HELM_PLUGINS
          value: /custom-tools/helm-plugins/
        - name: HELM_SECRETS_CURL_PATH
          value: /custom-tools/curl
        - name: HELM_SECRETS_SOPS_PATH
          value: /custom-tools/sops
        - name: HELM_SECRETS_VALS_PATH
          value: /custom-tools/vals
        - name: HELM_SECRETS_KUBECTL_PATH
          value: /custom-tools/kubectl
        - name: HELM_SECRETS_BACKEND
          value: sops
        # https://github.com/jkroepke/helm-secrets/wiki/Security-in-shared-environments
        - name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
          value: "false"
        - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
          value: "true"
        - name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
          value: "false"
        - name: HELM_SECRETS_WRAPPER_ENABLED
          value: "true"
        - name: HELM_SECRETS_DECRYPT_SECRETS_IN_TMP_DIR
          value: "true"
        - name: HELM_SECRETS_HELM_PATH
          value: /usr/local/bin/helm
        # For age
        - name: SOPS_AGE_KEY_FILE
          value: /helm-secrets-private-keys/key.txt
    volumes:
        - name: custom-tools
          emptyDir: {}
        # kubectl create secret generic helm-secrets-private-keys --from-file=key.asc=assets/gpg/private2.gpg
        - name: helm-secrets-private-keys
          secret:
            secretName: helm-secrets-private-keys
    volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
        - mountPath: /usr/local/sbin/helm
          subPath: helm
          name: custom-tools
        - mountPath: /usr/local/bin/kustomize
          name: custom-tools
          subPath: kustomize
        - mountPath: /usr/local/bin/ksops
          name: custom-tools
          subPath: ksops
        - mountPath: /helm-secrets-private-keys/
          name: helm-secrets-private-keys
    initContainers:
        - name: gitops-tools
          image: ajaykumar4/gitops-tools:latest
          imagePullPolicy: Always
          command:
            - sh
            - -ec
          args:
            - |
              mkdir -p /custom-tools/
              cp -rf /gitops-tools/* /custom-tools
              chmod +x /custom-tools/*
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ezpdaxrm9fgadmps3ru070f6kds27szenmr7jaz0d9f4vtm230qtwz7l0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRHNSTWpZOTdXU283NnpW
            Z2NNa2xhTUtrdmFidEIydjJaSUVsOGdIclM0CnhFT1ZIa2l1dEYrZlVQcnpVcWVG
            MHNocVBqbGdsbkdSV2VadkVzR2J1REEKLS0tIEZXWGZJc3pTNWZxa2Q0WGdBVS90
            TzlGR0RQcDFSUTI0eUJwRTBkcEZVZkkKmui4UjpqgJ9pK2ymuhNvufa8sC2w7z6I
            71h+u4NwcCGFdZ7NgSxmTWo78Ejyw8OY/1pv5b9U4yFzGxsY3t581A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T19:53:21Z"
    mac: ENC[AES256_GCM,data:EkWJJCXzKP7O3dKPhi2DzLNot69DC/155smemLgSWONeY2YZY5LqbzT2D8thc1o016KbrcFJf3veC2I5OksnvzRdPkfXX+2ECV2ZcmjgN+IDYBDCpbBNj7s9jauJLONgSHZ72/SJ+iFhEpC7rDNdjf23kgeRnVHZmPWT4wzdjKI=,iv:udswSHYoGNuEzE7Z1byPSL3n3z32z66IFH7iRpSPOa8=,tag:5tMa6byq49857wCd5VizSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
