fullnameOverride: external-dns
provider: cloudflare
env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
            name: external-dns-secret
            key: api-token
extraArgs:
    - --ingress-class=external
    - --cloudflare-proxied
    - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
    - --crd-source-kind=DNSEndpoint
policy: sync
sources:
    - crd
    - ingress
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
    - przmo.com
serviceMonitor:
    enabled: true
podAnnotations:
    secret.reloader.stakater.com/reload: external-dns-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ezpdaxrm9fgadmps3ru070f6kds27szenmr7jaz0d9f4vtm230qtwz7l0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZkp0RkpUZTRpNzF6SXFT
            ZDdLY2xSQmNhZ2FvdmZSK0tBMGtKYnpMMEdvCk1JSDh5TXFLQ3pCTXZZNEFHUldK
            N3RBVHJheW5nQWZsbXZqWWJFbit3SzAKLS0tIEZicXpiM2dmL2VIbmR3M2lrek1D
            ZWs2N1M2Sk5DdVpkY2kvelRZT3V5QVkKC4Xa0hGIBTYEnhj0AuWMlTJj0+Krff5k
            Pspourez+EwdRZ0RviIeoBqLQiB5b1p/6nEeWuJ0QqOMpgSJKusPfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T20:37:12Z"
    mac: ENC[AES256_GCM,data:bjXG5RR+L/ZOseDSgsqT0WL2Ec8rUe6t8yvsXcoodi2LGKNxMQKOH3Q48RkfkEveOXmbwMaekbcnmy5t0G2R38ghSDoOQjigaV8fOd5GorqP3UEYl4OxfZbmcq8tNSGfxuYIl7ikbC0Fj69FlErEnAfGT4g4agEXvF2MChj+Qjc=,iv:QncBJ498xPK8+WNecBNLnKJW62bAT0MQl4eNvKn3znE=,tag:U+WkkQC9qvvXbHbGJxX4Hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
