apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:jUhUX9HldCI8vexKpW0UtBEy+w4TrFhTZRJA93EoZ6GX/i5D2WitSg==,iv:q5Lvh1LfUGdvjk+pke/OWt/sJ6SK11QhjtQDHTnuj0o=,tag:kj9bPHlX+LFHlKRGnYUtwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ws8tm4vrmhjvd0qqwxqshfz42nt6q4k5wwgqsuxyun0667dws59s79u6nc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcHN3MEdZM29PcnVlY053
            UDBJVHo3aDl1cXFuejN5VExJaVlDdVIvNXdjCnNtMkl5andocUp1aHZMVkVOQ0Qz
            Q0FlbVJKWHNkcmhGTEdJY2h1ZVBZbkEKLS0tIEFBOG8zZGtMcVhuNDRyOS9McWEz
            OTkveW5LOTFOcjA1azZSempMVWRjZ1EKkgzjUGnwEQEexqs8lfp4XrrXwJWhi/ed
            VpTrsvcyKlj0JwEiE3CIOEw7yOrfzU0QAKtl3ZtApuazNBbSMUVZ4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T01:36:33Z"
    mac: ENC[AES256_GCM,data:uzfHOIrXP1fK6AFi32ChhvaxFTLm9d6ZXtfMEhTAkJ0uIVv4swyIAW+KSw/OOJSJoJj89bmfrzfaYqE9OwUe2ckfeSR3Rp4qGcguKMDHE0GKiHQbswTqCwbYKiFS+LxkQAwOjEecNOBl5QE9btG8LC9rIwnlmuf1yZbCCrXara8=,iv:fbkG7HCKRqkN1igId4iOvk5IQ6NF1g/Wcvw0JMjyJLI=,tag:UvzI7dJTPLhMVVp2ScWG2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
