apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-staging
spec:
    acme:
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        email: harrisonboyd400@gmail.com
        privateKeySecretRef:
            name: letsencrypt-staging
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: cert-manager-secret
                        key: api-token
              selector:
                dnsZones:
                    - przmo.com
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ezpdaxrm9fgadmps3ru070f6kds27szenmr7jaz0d9f4vtm230qtwz7l0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETTRXQmxMc0xVaW5mSTky
            SkRROG1DTTlwYXU5K3lRK1cwT1VuMkhrVDBvCk1LV1dRYTlvazNCYzAzNjErM3BE
            c09jdTFtdXJhRVByMUtFV0wvTEJwdlEKLS0tIEhjRENWRTFBWUJUR0tLZGttU1Ra
            N1RZSE50MElRR3h0eEhjM09iWVJ3dWcK04T7SpmjaYMGdfHr2/munpnHZkUtCJxt
            tc/uf8iC0tPcW5IYsvtp4rmvjITc4TFPpDn4GvAoSHWvGYtzmb439w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T20:37:12Z"
    mac: ENC[AES256_GCM,data:c+pHnN1HLzs2OMHQ7+arK6uB6zMIlBNVUoHSsLDqsfnXDHP34uUqXiwrUidOrYji1ioery/uvoYFn7nSL35nPyXfMNnGGFwX6SRMKe/hXUxNVrKkJBz8H1iUB+QisY8HBqRkTTGQPl/58sJH9Ne4zc1Mjef9kvEElgxWjBTFs9o=,iv:M3DVjFrk1U5OKt6UkxtRPnAyP6qdBzKdOVQP17lgbEk=,tag:uTOuFS0Nvwi3yXdiGlRyQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-production
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: harrisonboyd400@gmail.com
        privateKeySecretRef:
            name: letsencrypt-production
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: cert-manager-secret
                        key: api-token
              selector:
                dnsZones:
                    - przmo.com
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ezpdaxrm9fgadmps3ru070f6kds27szenmr7jaz0d9f4vtm230qtwz7l0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETTRXQmxMc0xVaW5mSTky
            SkRROG1DTTlwYXU5K3lRK1cwT1VuMkhrVDBvCk1LV1dRYTlvazNCYzAzNjErM3BE
            c09jdTFtdXJhRVByMUtFV0wvTEJwdlEKLS0tIEhjRENWRTFBWUJUR0tLZGttU1Ra
            N1RZSE50MElRR3h0eEhjM09iWVJ3dWcK04T7SpmjaYMGdfHr2/munpnHZkUtCJxt
            tc/uf8iC0tPcW5IYsvtp4rmvjITc4TFPpDn4GvAoSHWvGYtzmb439w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T20:37:12Z"
    mac: ENC[AES256_GCM,data:c+pHnN1HLzs2OMHQ7+arK6uB6zMIlBNVUoHSsLDqsfnXDHP34uUqXiwrUidOrYji1ioery/uvoYFn7nSL35nPyXfMNnGGFwX6SRMKe/hXUxNVrKkJBz8H1iUB+QisY8HBqRkTTGQPl/58sJH9Ne4zc1Mjef9kvEElgxWjBTFs9o=,iv:M3DVjFrk1U5OKt6UkxtRPnAyP6qdBzKdOVQP17lgbEk=,tag:uTOuFS0Nvwi3yXdiGlRyQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
