apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:jK1jO9N56959RCwsQYGV3p7hF5XiP5SGVWzYR6HbvFTaUBkSsHMFpQ==,iv:tCdzmCbblwbfUDBS18rHkCPf3RSEVuJTatJ7zkxfn0U=,tag:Xbtwda9fWAkIo/aGcA7C3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ezpdaxrm9fgadmps3ru070f6kds27szenmr7jaz0d9f4vtm230qtwz7l0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1T01sUi9CY0FPTjBWVXBr
            Q3ByRWpzaVBnVGFWMS81Z3NYSDRtQWVydEJJClpITFFIWlFzWjhIQ2RtMjJVOG55
            Sm9xcjZHcU50Q0xOZHNJMEJWR0ROL3cKLS0tIGlZTmpkMk1sM2xid2J0RVBJQjFx
            YmN0YjRDMHdUMHF2MWhQYnd1Vjk0RUUKQvdcZxN0pwQ1vmfp/+UGXCTdy6FGxGFr
            ZMHisJaj9Oh+Dj/tpcHhF38y8L09E5IXf1a6DwPjs1Cks1xAaemrhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T20:37:12Z"
    mac: ENC[AES256_GCM,data:2kXcOrgC/TqoF+ZMbdl4uTIC3cctyy7ueZRbpPdRL3kNB6Ad3Qb72i1W14L5WXtJRTpXv0B4HnTvEGPQWVgkS7USXNvy2BxLUPTMQsTuT0HMtStqgarJmjTlZxG5k30+mrkdRbem5f/Ib4PxGk7KZHUhDwycsdAhq9oI8VxClwU=,iv:ixykmzTEiEU8Vk1CXldUWQCgT4mfD9IYx1DiCMlQ8CA=,tag:sL3o6asz1zEDAreUHK2PYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
