apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:UDN6F5BDbvToQFlpHKBZmkUR8oBARPATCeb7zgnxOOBRE55O3jVebA==,iv:3XkExgaeYf/olLWaH5sw9rzQ00YPXAAeROf5jab1VBI=,tag:6FmtazY+NC0bJWHZQf5VxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ws8tm4vrmhjvd0qqwxqshfz42nt6q4k5wwgqsuxyun0667dws59s79u6nc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDckNvT3Y4cU9NcUJFSStm
            MnZnSkUxZVgxU2FPZHdVM1hON3Y0R1htcmlvCmMzQUNJN3BiQnpVaU9tWnA2NkdO
            aEFDT0dFL0hSMTFuaWtPcjQ0NVdaNE0KLS0tIHhkZFNMRW1ySTFYN0oxSmlXSTh2
            c2txQWYzOUMrY0ZGQjVtOFVRK2ppNFEKQJ7JFJ2ysx/G8l1/Ksnr55tNPPGowkQk
            oq5tGHQgJ+UQraDdpgrEPNobteoLnuLkv5NOnXzShUE+FoWT3xI4Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T01:36:33Z"
    mac: ENC[AES256_GCM,data:xtzgqRrMGfts3WR2wTdFy09DCpircwlJyZIniIbZGHCz9OlyRTwNOZnpBsPfSQdbKMOCSrF4g4P1CfzoC/b2bqiHzlHyhUfNWeA3PInPyUOxvqnA0C4nYmiBkOVYO8JmsGpPSoMSPVktgueZvx6uV1LIsAaJBeASsayOJgV5JkY=,iv:MZQDPFyLTnzkgfA7v6BhOxdIpuaUifqUaxfb8SrVCus=,tag:Pq+5n3j9VpxSTBeI2SqNeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
