apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: przmo-com-production
spec:
    secretName: przmo-com-production-tls
    issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
    commonName: przmo.com
    dnsNames:
        - przmo.com
        - '*.przmo.com'
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ezpdaxrm9fgadmps3ru070f6kds27szenmr7jaz0d9f4vtm230qtwz7l0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVFA3eUdjOHRUVDkxUEZm
            OUsvMG5HdU5QeWtHZ2h6YTVpc1VIRGtGNjBRCnI4WGtxaW9tTHhCeFhsNEwxTkJv
            TUNqV3lONUdySHQrWU5FalRkS1BrNnMKLS0tIHEyUTlxcFplTlRzUUc1cDMwTkI2
            aDkxTUV3aGkzVytuYVlrdUpRRUJQaW8Kn/bM+PGKncIn9h/h83iBED5+miUigSKn
            s697vOBPy7Ffx0DRf+kqEizghgHJ3MIQLrlumSgt7XAnLzdawUxd9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T20:37:12Z"
    mac: ENC[AES256_GCM,data:LWvbAYehvYsefJNOSsFgdEd6Tot7FkMjkngB2l4t3HvMaKpTl0HBduPrz7OcAhhYVXdPvQlk/kRIf0jbdb/HtCyYu8+0+88EX8henkXokRBe2++twGa5fxCCnN61X4gkmbFjIXgMMNviMfM3RSlp4WKEChidnsy2DWYtAgP+CJc=,iv:HlmD/+fWdcvaVXXn2rr8OJVTG7dCaVoJOP/FsgjRnMk=,tag:hkVDoK3dqW/s7PcFXAp6tA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
