apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: przmo-com-staging
spec:
    secretName: przmo-com-staging-tls
    issuerRef:
        name: letsencrypt-staging
        kind: ClusterIssuer
    commonName: przmo.com
    dnsNames:
        - przmo.com
        - '*.przmo.com'
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ezpdaxrm9fgadmps3ru070f6kds27szenmr7jaz0d9f4vtm230qtwz7l0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHa1ZDaWdHRWNpRDg2eUlx
            UDlrVlUzSjRzNDFEN0huMUY3Z3hJSmExRkNVCkFST2Z5cC84UnJNc1JUdTZpNFF3
            cUpGTXVBc3RPakQyNkNGNGtibE8wWmsKLS0tIEl4RXVqN0ZQZTV4THVMcjgwVk1L
            dXAyVW01TkNTNktJYUh3L2swaUZjUlkKjj7gTFnCDC3ckH3hiaYosM+UceNp1FIv
            2O1krzEF59DDx0CKk/vpRvykDI6TTp2T+Eye/tCwmyMY9aY9krWFVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T20:37:12Z"
    mac: ENC[AES256_GCM,data:ryy8mFV/vByhuuMc0IUd7bl+m1Wa6kICKN4DcRnIoBLBFt4Uw9gbO5U/4h+S2YB92dvDpxN1RdC7fcAsSNOjL80WJcKawdD/aRy9nVtfk3AQPU0AGnTHeonN8uqyj8lQMxae/JSCVasxOeskLAf1rESDGK1eR+oyYlGkLNWIDyQ=,iv:99nZ2RTd5MV+uWD823QmBOr9edvVBVoLct4xKQByvC4=,tag:or4czbdrmayxk4lva6YRKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
