apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:zCX69GPuRXaKZ/8Ci76UaEzJklAm7f/UzW4P9butiZyVtG21,iv:1pLVQyzX+t1TnFG04omrKKIMdOflt9XzPUx0d4CIvm4=,tag:57SKf8Uge36LMPQGrA4POw==,type:str]
    credentials.json: ENC[AES256_GCM,data:AJbmksVNR9jZNKVcMwm6FcHZnAomePQi+qAUw3ElyXwMldMBiblxDBZoAxw6aQwlcwJdHHE7EZGVABTGz4YdBTfS3F4fqxvPj0R38mjYcoexTX0Ubr1mjV1bVbkD7uav3SSeOIC9m2l60/tv+nJnuyevqiNCcq1GVyBuftA+TieqmQwGp92faJmqUA1Rb2ZBGlBPjFuiOKec+JIDaOLc671lZA/oJuxpZP++cMqR+OaxdTIrUzxjrc3k5iMUFuaYGGGFscK1bVwtagjX59csxKySPKJP8O9CD8YD/Ca48YAkX5y/CvL1BIBBUpwQaudLRirsoCUl8RC6MRWQ3+Qcu9vkZ8C9X6h/HSsu0L48/cubpHl1Kvatlq8Qyx6qZ4LVwnrOvVnSjNK1b2mELCKm9pPRfMLO6IHuIneb,iv:Y/FpUZJNgeNVnr0LYQN/eG/bvuS3zb8tlo53q1DFyik=,tag:RrxqHw7GEaiX9B5DUKhiJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ws8tm4vrmhjvd0qqwxqshfz42nt6q4k5wwgqsuxyun0667dws59s79u6nc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbHFVT0xNWGZEdFZLY0h2
            WTJtYWJYa24xbkQ4V28xdWRRQnhqS1I2eHk0ClJ3SDFIcTF2cHNIRy9WalhRSzNT
            cTZzR1o0aTVGdFB6WlBVWnJObVU1VU0KLS0tIC9qNEtURGh2MXMwYUhveGtacFcx
            elJTS1BGWXlXWGlxMDB2dU9iWi9XK2sKhb3jN5vsIb6XQ1V+hjBmAVJo6kvmV7pR
            aa2bFuPQlJjMxwIOWmwye1I0Sm2zS0tcmg7fxtIUeuoc2D/IVYagKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T01:36:33Z"
    mac: ENC[AES256_GCM,data:EcIuGkk3DlqechGbIKTb0dTmvuH9epZy+kVgK77v8yi92W5vI/SWyjXX8Z0UVFs4QWpPuMcL/q37OXJe9tIZ+sRInFA3xQ5KjASeQhQexOktUNgSnjILbqHosyOsjhMnKzfTrAeknOOW4fJXSs3Kb6R2NNWfxytJRyJ6NcqlizA=,iv:Wt1HszzYq+CMu7VciZteO5yDAmZ9YyEwXmgyvpPbrdA=,tag:fkPidTgykz1b35jpipH89A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
