fullnameOverride: k8s-gateway
domain: przmo.com
ttl: 1
service:
    type: LoadBalancer
    port: 53
    annotations:
        io.cilium/lb-ipam-ips: 10.0.1.2
    externalTrafficPolicy: Cluster
watchedResources:
    - Ingress
    - Service
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ezpdaxrm9fgadmps3ru070f6kds27szenmr7jaz0d9f4vtm230qtwz7l0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Vk1oQ2lHeDJxRWJ2dWM0
            WGdOUjVmM21ZTXpvaEhXNjdHc0hBMzJiVUJJCnRLNk9IU0ZjNTRSRWNLVWprR1VT
            NFlwRFB2bk1sZnMzTW1MVVlZYkc3QzQKLS0tIHVMUDZHaUo3K1plZlFXRVJSOVZ1
            K3R1Sjcxbm5sVndndkNJd0gveEpoeFUKIjelA08inRtN1crDaPNAsj4mhh7NVqTY
            htWCPHGwN7cleg2sTTko1LT77uncuP9t7hlnd7jDP4RzLfRRUw1y/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T20:37:12Z"
    mac: ENC[AES256_GCM,data:0lMID6PxUWQaTBD4wnHN4Iy2Ka8MeuqaZuGhn5bmjZXoYnIOIqiz4hKq2Fdd2TCWxmmOYiNF/3da2IfAGG7qdD7wgP1Jf8r2DwCWpKgCLFC4SdofI11TRFOBbFgEBlL8f6HiV1Vj+c5fr9dbYIGtQ6URPytniV0tW+lr24TzQrk=,iv:harLRsJpT3UVbukpQ7/e4KKhGtaXRFqXcuV1eKazH68=,tag:8Pa4FNaqI0y2wTEWeMlLDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
